// Business Alignment · Module 5 (lesson "Module 4"): Boundaries & Capacity
// Seeded to Firestore courses/business-alignment/modules/5.
// Brand voice: grounded, clear, no hype, no em dashes.

module.exports = {
  "id": 5,
  "title": "Module 4: Boundaries & Capacity",
  "subtitle": "Protect the life the business is supposed to fund, with numbers rather than willpower.",
  "pillar": "Realign the Business",
  "duration": "22 min",
  "published": true,
  "html": `
<p>Here is the sentence that undoes most of what you have built in the last three modules: sure, we can make that work.</p>
<p>Good positioning and honest offers still fail when the business has no defined capacity, because every well intentioned yes is taken out of the same finite account and nobody is tracking the balance. This module puts a number on the account and then defends it in a way that does not require you to be disciplined at four in the afternoon on a hard day.</p>

<h2>Capacity is a number you have never written down</h2>
<p>Ask an owner how much work they can take and you usually get a feeling. Feelings about capacity are generated by the current moment, which is why the same person says yes in a quiet week and resents it in a busy one.</p>
<p>Calculate it instead. Four steps, ten minutes.</p>
<ol>
<li><strong>Total working hours per week</strong> you actually want to work. Start from the life, not the business. If the honest number is 45, write 45, not 60 because that is what this year has looked like.</li>
<li><strong>Subtract the non delivery load:</strong> sales, marketing, admin, finance, and the hours you owe to building the business rather than running it. Use your Part A time split from the audit, because guessing here is what breaks the whole calculation.</li>
<li><strong>What remains is deliverable capacity.</strong> Usually a number that startles the owner, often somewhere between half and two thirds of the total.</li>
<li><strong>Subtract a buffer of about fifteen percent</strong> for the things that are not optional and never fit in an estimate: a client emergency, a sick day, a piece of work that ran long. A plan with no buffer is a plan that fails on its first normal week.</li>
</ol>
<p>That final figure is your capacity. Divide it by the average delivery hours of your main offer and you have the maximum number of active engagements you can hold at once. Write that number down. It is the single most useful number in this course, because it converts an emotional decision into an arithmetic one.</p>

<h3>What happens at the boundary</h3>
<p>When you are at capacity and a good opportunity arrives, you have exactly four honest options. Not three, and not "somehow."</p>
<ul>
<li><strong>Say no,</strong> cleanly, with a referral if you have one.</li>
<li><strong>Schedule it later,</strong> at a real start date, when capacity actually opens.</li>
<li><strong>Trade,</strong> by ending or rescoping something existing to make room, deliberately and with the client told.</li>
<li><strong>Raise the price</strong> so that exceeding your capacity is at least priced as the exception it is, which naturally limits how often it happens.</li>
</ul>
<p>Absorbing it into your evenings is not a fifth option. It is a decision to take the hours from the life the business is supposed to fund, made quietly, with no one to negotiate with. If your audit showed a low boundaries score, this is almost certainly where it came from.</p>

<h2>Boundaries are terms, not moods</h2>
<p>Most owners think of boundaries as something they have to enforce with personality. Stated in advance and in writing, they stop being about personality at all. A boundary that lives in your head is a preference you will defend inconsistently, and clients reasonably respond to what they were told rather than what you meant.</p>
<p>The five worth defining, in plain language, where a client can see them:</p>
<ul>
<li><strong>Working hours.</strong> When you work and when you do not. Include the day of the week you protect, if you have one.</li>
<li><strong>Response time.</strong> How quickly a message gets answered, and what counts as urgent. Undefined response times default to instant, because that is what the fastest reply you ever sent taught them.</li>
<li><strong>Scope.</strong> What the engagement includes and what triggers a new conversation about money. The trigger matters more than the list.</li>
<li><strong>Revisions or rounds.</strong> How many, and what happens after that. Most scope creep is unnumbered revisions.</li>
<li><strong>Channels.</strong> Where work happens. A business where decisions arrive by text at nine at night has a channel problem, not a client problem.</li>
</ul>
<p>Put them in the agreement, say them in the first call, and repeat them at the start of the engagement. A boundary introduced three months in reads as a complaint. The same boundary introduced at the start reads as professionalism, and buyers in fact find it reassuring, because a supplier with defined terms looks like one who has done this before.</p>

<h3>How to hold one without damaging the relationship</h3>
<p>Three sentences, in this order, and it works for nearly every version of this conversation.</p>
<blockquote><strong>Acknowledge:</strong> "That is a real deadline and I understand why it matters."<br>
<strong>State the constraint:</strong> "I am at capacity through the fifteenth."<br>
<strong>Offer a real option:</strong> "I can start it on the sixteenth, or I can move the reporting work to next month and start it Thursday. Which is more useful to you?"</blockquote>
<p>No apology, no explanation of your schedule, no negotiation of your competence. The third sentence is what keeps the relationship intact, because you are not refusing to help, you are declining to pretend that time is elastic. Most clients accept this immediately. The ones who do not are telling you something useful about the relationship you scored in module 3.</p>

<h2>The boundary you owe the business, not the client</h2>
<p>One boundary has no external party: the time set aside to work on the business rather than in it. It is the first thing dropped in a busy week, and dropping it is what guarantees the next busy week.</p>
<p>Treat it as an engagement with a client who happens to be your company. It has a time, it does not move for anything that is merely urgent, and it produces something. Without it, module 6 has nowhere to live, and the offer you named at the end of module 3 never gets built, which means your capacity problem is permanent by design.</p>

<h2>When saying no is genuinely expensive</h2>
<p>Boundary advice tends to assume the owner can afford to turn work away. Sometimes you cannot, and pretending otherwise is how a course loses credibility with the people who most need it.</p>
<p>If one client is a third of your revenue, the honest position is that you have less leverage than the advice above implies, and the first job is not to hold a firmer line. It is to reduce the dependency, because a boundary you cannot afford to enforce is not a boundary, it is a bluff, and clients read bluffs accurately.</p>
<p>Three moves, in order, when the no is too expensive to say yet.</p>
<ol>
<li><strong>Buy time rather than agreeing.</strong> "Let me look at the schedule and come back to you this afternoon" is available in every conversation, and it converts a pressured yes into a considered decision. Most bad commitments are made in the sixty seconds after being asked.</li>
<li><strong>Trade instead of refusing.</strong> "I can do that if we move the other deliverable to the following week. Which do you want first?" You have not said no, you have made the cost visible, and a client who then chooses is a client who now understands your capacity.</li>
<li><strong>Work the concentration number.</strong> A dependency is reduced by adding revenue, not by feeling braver. One new client at a workable rate changes what you can afford to say, so until that exists, treat the pipeline as the boundary work.</li>
</ol>
<p>Write down what your concentration would have to be before you could hold your terms with everyone, without exception. That figure is a real business target and it belongs in module 5's metrics, not in a list of things you wish you were better at.</p>

<h2>Rewirement: Set one boundary this week</h2>
<p>Target: <strong>capacity calculated, one boundary stated out loud to a real person.</strong></p>
<ol>
<li><strong>Calculate your capacity.</strong> All four steps, with the buffer. Write the final hours figure and the maximum number of concurrent engagements.</li>
<li><strong>Compare it to what you are carrying now.</strong> If you are over, write by how much. That number is the honest size of your current overcommitment.</li>
<li><strong>Write your five terms</strong> in plain language: hours, response time, scope, rounds, channels.</li>
<li><strong>Pick the one that is costing you most</strong> and state it this week to an actual client, in the three sentence format. Not on your website. To a person.</li>
<li><strong>Put the on the business hour in your calendar,</strong> weekly, with a start time, and mark it as unavailable.</li>
<li><strong>Write down what you will say</strong> the next time you are at capacity and something good arrives. Word for word, so you are reading rather than improvising under pressure.</li>
</ol>
<p><strong>Common mistake:</strong> announcing every new boundary to everyone at once, in a message that reads like a grievance. Introduce terms quietly and apply them consistently. Consistency is what makes a boundary real, and one boundary held for three months teaches your clients more than a policy update nobody asked for.</p>
<p>Next module goes to the numbers: what to track so that growth means a better business to own rather than just a bigger one.</p>`,
  "workbook": {
    "reflection": "Calculate your true deliverable capacity in hours, then compare it to what you are carrying right now. Write the gap as a number, and write what that gap has been taking from the life this business is supposed to fund.",
    "action": "Write your five terms in plain language, pick the one costing you most, and state it to an actual client this week using acknowledge, constraint, real option. Then put the weekly on the business hour in your calendar as unavailable time.",
    "prompts": [
      "How many hours a week do you actually want to work? Start from the life, not the business.",
      "What is your non delivery load in hours: sales, marketing, admin, finance, building?",
      "What is your deliverable capacity after the fifteen percent buffer, and how many concurrent engagements is that?",
      "By how much are you over capacity right now?",
      "Write your five terms: working hours, response time, scope, rounds, channels.",
      "Which boundary is costing you the most, and who are you stating it to this week?",
      "Write, word for word, what you will say the next time you are at capacity and something good arrives.",
      "When is your weekly on the business hour, and what will you protect it from?"
    ]
  },
  "summary": [
    "Capacity is a number, not a feeling. Feelings about capacity are generated by whether this week is busy.",
    "Calculate it: hours you want to work, minus the non delivery load, minus a fifteen percent buffer.",
    "At the boundary there are four honest options: no, later, trade, or price it as the exception. Absorbing it into your evenings is not one.",
    "A boundary in your head is a preference. Stated in the agreement and the first call, it is a term.",
    "Acknowledge, state the constraint, offer a real option. No apology and no negotiation of your competence.",
    "The boundary with no client attached, time on the business rather than in it, is the one that keeps the others possible."
  ]
};
