// 1P Certified Life Coach · written exam bank.
// Seeded to Firestore examBank/1p-clc/questions/q### by scripts/seed-clc.js.
// Each: { prompt, choices[4], correctIndex, topic }. startExam draws
// config/certification.examQuestionCount at random from active questions.
//
// topic is one of: foundations, align, session, identity, questions,
// navigation, engagement, certification. It is metadata for coverage review
// and future filtered draws; startExam ignores it today.
// House rules for anything added here: four choices, one clearly best answer,
// three plausible distractors, no trick questions, no "all of the above", no
// price questions, no em dashes, and nothing that depends on the exact wording
// of a module.

module.exports = [
  // ---- foundations ----------------------------------------------------
  { prompt: 'A client asks, "What would you do in my situation?" The strongest coaching response is to:', choices: ['Share what worked for you, since they asked directly', 'Redirect with a question that returns ownership, such as "What options do you see?"', 'Decline to answer and change the subject', 'Give advice but label it clearly as advice'], correctIndex: 1, topic: 'foundations' },
  { prompt: 'A client repeatedly describes symptoms of clinical depression. The certified coach should:', choices: ['Design a habit plan to improve their mood', 'Coach harder on mindset', 'Refer them to a licensed mental health professional with care, and stay within coaching scope', 'End the engagement immediately without explanation'], correctIndex: 2, topic: 'foundations' },
  { prompt: 'Confidentiality in a coaching engagement should be:', choices: ['Implied and never discussed', 'Stated in the agreement before coaching begins, with its limits named', 'Absolute with no exceptions of any kind', 'Optional for practice clients'], correctIndex: 1, topic: 'foundations' },
  { prompt: 'The compounding logic at the heart of The One Percent is:', choices: ['Massive action in short bursts', 'Becoming one percent better every day through small, consistent, aligned progress', 'Working more hours than anyone else', 'Waiting for motivation before acting'], correctIndex: 1, topic: 'foundations' },
  { prompt: 'A client says, "Just tell me what to do, you have already been where I am." The clearest way to describe how coaching differs from mentoring is:', choices: ['A mentor hands down a path they walked; a coach helps the client build a path that fits them', 'A mentor asks questions and a coach gives answers', 'A mentor works on the past and a coach works on the present', 'There is no real difference once trust has been built'], correctIndex: 0, topic: 'foundations' },
  { prompt: 'Mid-session you hold a piece of information the client genuinely needs. The cleanest way to offer it is to:', choices: ['Work it into a question so it does not sound like advice', 'Hold it until the end of the engagement', 'Share it at length so the client has the full context', 'Ask permission, give it in a sentence or two, and hand the session back'], correctIndex: 3, topic: 'foundations' },

  // ---- align ----------------------------------------------------------
  { prompt: 'The five stages of A.L.I.G.N., in order, are:', choices: ['Awareness, Leadership, Identity, Growth, Navigation', 'Alignment, Learning, Intention, Goals, Navigation', 'Awareness, Listening, Identity, Growth, Negotiation', 'Action, Leadership, Insight, Growth, Navigation'], correctIndex: 0, topic: 'align' },
  { prompt: 'In A.L.I.G.N., the stage that centers on taking ownership of your story is:', choices: ['Leadership', 'Awareness', 'Navigation', 'Growth'], correctIndex: 0, topic: 'align' },
  { prompt: 'Growth, as the G of A.L.I.G.N., is best described as:', choices: ['Adding more goals to the plan', 'Measuring progress against a baseline', 'Choosing expansion over comfort', 'Seeing the belief clearly'], correctIndex: 2, topic: 'align' },
  { prompt: 'A client describes their pattern in accurate detail, blames their schedule for it, and takes no part in it. The stage to work is:', choices: ['Navigation, because they need a better plan', 'Growth, because they need a larger goal', 'Identity, because the belief needs rewriting', 'Leadership, because ownership has not happened yet'], correctIndex: 3, topic: 'align' },
  { prompt: 'A coach skips Awareness and starts building an action plan in session one. The most likely result is:', choices: ['Faster results, because the client is motivated early', 'A client who becomes dependent on the coach for structure', 'A client who ends the engagement in the first month', 'Action that does not hold, because the belief driving the pattern was never seen'], correctIndex: 3, topic: 'align' },
  { prompt: 'Navigation is the stage in which the client:', choices: ['Executes the path forward', 'Names the belief for the first time', 'Rewrites who they believe they are', 'Decides whether coaching is right for them'], correctIndex: 0, topic: 'align' },

  // ---- session --------------------------------------------------------
  { prompt: 'Level-three listening means hearing:', choices: ['The exact words the client says', 'The meaning behind the words', 'What is not being said: energy shifts, avoided subjects, repeated words', 'The advice the client is hoping for'], correctIndex: 2, topic: 'session' },
  { prompt: 'The 1P session spine is:', choices: ['Small talk, problem, solution, homework', 'Intention, session goal, explore, insight, action, accountability', 'Review, advice, plan, close', 'Goal, obstacles, options, way forward, celebration, referral'], correctIndex: 1, topic: 'session' },
  { prompt: 'Level-two listening means hearing:', choices: ['The words exactly as spoken', 'What the client is carefully avoiding', 'The meaning behind the words', 'Your own next question forming'], correctIndex: 2, topic: 'session' },
  { prompt: 'The reason a session opens with intention is to:', choices: ['Settle both people and name what the client is bringing before the work starts', 'Review everything the client failed to do last week', 'Give the coach time to find their notes', 'Confirm fees and scheduling for the engagement'], correctIndex: 0, topic: 'session' },
  { prompt: 'A client arrives with three problems and wants all of them covered in 50 minutes. The strongest move is to:', choices: ['Cover all three quickly so nothing is ignored', 'Choose the one you believe matters most and start there', 'Reschedule for a longer session', 'Ask which one, if it moved today, would matter most, and make that the session goal'], correctIndex: 3, topic: 'session' },
  { prompt: 'Ten minutes remain and the client is still exploring. The session spine says your next job is to:', choices: ['Let the exploration run and skip the close', 'Summarize the session on the client\'s behalf and end', 'Open a new line of questioning to go deeper', 'Move toward insight, action, and accountability so the client leaves with something to carry'], correctIndex: 3, topic: 'session' },

  // ---- identity -------------------------------------------------------
  { prompt: 'Why does the 1P method work at the identity layer rather than the behavior layer alone?', choices: ['Identity work is faster', 'Behavior change that contradicts identity does not hold', 'Clients prefer talking about identity', 'Behavior change is impossible without a coach'], correctIndex: 1, topic: 'identity' },
  { prompt: 'Misalignment in a successful-on-paper client is most often rooted in:', choices: ['Laziness', 'A values conflict between what they say matters and how they operate', 'Lack of information', 'Too few goals'], correctIndex: 1, topic: 'identity' },
  { prompt: 'A client says, "I am just not a disciplined person." The strongest first move is to:', choices: ['Ask where that sentence came from and when they first believed it', 'Disagree and list the evidence of their discipline', 'Build a habit tracker to prove the belief wrong', 'Accept it and design the plan around the limitation'], correctIndex: 0, topic: 'identity' },
  { prompt: 'A client reaches the outcome they wanted and feels nothing. The most useful read is:', choices: ['They set the goal too low', 'They need a larger goal set immediately', 'The goal belonged to an identity they never actually chose', 'They are measuring progress the wrong way'], correctIndex: 2, topic: 'identity' },
  { prompt: 'The purpose of a values excavation is to:', choices: ['Help the client choose a better career', 'Rank the client goals from most to least important', 'Give the coach material for the next session', 'Surface what the client actually values and where their commitments contradict it'], correctIndex: 3, topic: 'identity' },
  { prompt: 'When a client states a limiting belief out loud, the 1P sequence is to:', choices: ['Challenge the belief, then hand them a replacement', 'Reframe it into a positive affirmation they repeat daily', 'Set it aside and work on behavior first', 'Surface the belief, trace the story that installed it, then coach them to write a truer one'], correctIndex: 3, topic: 'identity' },

  // ---- questions ------------------------------------------------------
  { prompt: 'A powerful coaching question is usually:', choices: ['Long and detailed so the client understands the context', 'Closed, so the client can answer quickly', 'Short, open, curious, and asked one at a time', 'Leading, so the client reaches the right conclusion'], correctIndex: 2, topic: 'questions' },
  { prompt: 'During a session the client falls silent after a strong question. You should:', choices: ['Rephrase the question immediately', 'Fill the silence with an example from your life', 'Hold the silence and let the client think', 'Move to the next agenda item'], correctIndex: 2, topic: 'questions' },
  { prompt: 'Which of these is the strongest coaching question?', choices: ['Have you thought about delegating more of that?', 'Do you think the real issue here might be fear?', 'What if you blocked your calendar, would that help?', 'What happens in the moment right before you say yes?'], correctIndex: 3, topic: 'questions' },
  { prompt: 'A coach asks three questions in a row without pausing. The main cost is:', choices: ['The client answers the easiest one and the real question is lost', 'The session runs past its scheduled end', 'The coach looks unprepared', 'The client stops trusting the framework'], correctIndex: 0, topic: 'questions' },
  { prompt: 'A client gives a quick, polished answer they have clearly given many times before. The strongest follow-up is to:', choices: ['Accept it and move to the next topic', 'Ask what sits underneath that answer', 'Offer your own interpretation of what they said', 'Move to action planning, since they are already clear'], correctIndex: 1, topic: 'questions' },
  { prompt: 'The 1P goal stack works because:', choices: ['Three goals are easier to remember than one', 'Outcome goals motivate people more than process goals do', 'Daily process connects to the outcome through who the client is becoming', 'Identity goals are the easiest to measure weekly'], correctIndex: 2, topic: 'questions' },

  // ---- navigation -----------------------------------------------------
  { prompt: 'The 1P goal stack, in full, is:', choices: ['Outcome goals only', 'Outcome, identity, and process goals', 'Daily, weekly, and monthly goals', 'Stretch, realistic, and safety goals'], correctIndex: 1, topic: 'navigation' },
  { prompt: 'Accountability in the 1P method is best described as:', choices: ['Applying pressure so the client performs', 'Honest measurement plus belief, never guilt', 'Checking in only when the client fails', 'Making the client report to you daily'], correctIndex: 1, topic: 'navigation' },
  { prompt: 'A client agrees to every plan but completes none of them. The first coaching move is to:', choices: ['Assign smaller tasks', 'Explore ownership: whose goal is this, really?', 'Add more accountability check-ins', 'End the engagement'], correctIndex: 1, topic: 'navigation' },
  { prompt: 'A client misses their committed action three weeks running. The strongest move is to:', choices: ['Look at the friction and the real constraints with them before touching motivation', 'Pause the engagement until they are ready to commit', 'Tell them you are disappointed so the miss carries weight', 'Assign the same action again with a firmer deadline'], correctIndex: 0, topic: 'navigation' },
  { prompt: 'Between-session accountability works best when it is:', choices: ['Daily reporting from the client to the coach', 'Left to the client to raise if they want it', 'Agreed in advance: what happens, in what channel, at what rhythm', 'Triggered only after a missed commitment'], correctIndex: 2, topic: 'navigation' },
  { prompt: 'In a progress review, drift is named by:', choices: ['Comparing this client to your other clients', 'Asking the client to explain themselves', 'Letting it pass this once to protect the relationship', 'Measuring against the baseline and stating plainly what you see, without shame'], correctIndex: 3, topic: 'navigation' },

  // ---- engagement -----------------------------------------------------
  { prompt: 'The discovery call exists primarily to:', choices: ['Close the sale as fast as possible', 'Serve the prospect with real clarity; the sale is a byproduct', 'Demonstrate how much you know', 'Qualify whether the client can afford you'], correctIndex: 1, topic: 'engagement' },
  { prompt: 'The audience the 1P method is built to serve is best described as:', choices: ['People who are successful on paper and misaligned in practice', 'People in crisis who need immediate clinical support', 'Early-career workers looking for a first promotion', 'Executives looking for industry-specific consulting'], correctIndex: 0, topic: 'engagement' },
  { prompt: 'Pricing confidence comes from:', choices: ['Matching the lowest price in your market', 'Explaining your certification at length', 'Clarity about the outcome your engagement produces and who it is for', 'Offering a guarantee that removes all client risk'], correctIndex: 2, topic: 'engagement' },
  { prompt: 'A licensed practitioner delivering the six-week A.L.I.G.N. client program should:', choices: ['Deliver the framework as designed and adapt pacing to the client', 'Rebuild the framework and release it under their own name', 'Blend it with another training body model so it feels broader', 'Drop the assessment to save session time'], correctIndex: 0, topic: 'engagement' },
  { prompt: 'A prospect on a discovery call is clearly not a fit for coaching right now. The right move is to:', choices: ['Sell a shorter package so they leave with something', 'Offer a lower price to reduce their risk', 'Enroll them and address the fit question later', 'Say so plainly and point them toward what would actually help'], correctIndex: 3, topic: 'engagement' },
  { prompt: 'The coaching agreement should be in place:', choices: ['After the first paid session', 'Only when a client asks for one', 'At the midpoint of the engagement', 'Before coaching begins, including with practice clients'], correctIndex: 3, topic: 'engagement' },

  // ---- certification --------------------------------------------------
  { prompt: 'The four criteria of the certification rubric are:', choices: ['Presence and Listening, Question Quality, Session Structure, Non-Advising', 'Energy, Charisma, Knowledge, Closing', 'Empathy, Advice Quality, Speed, Results', 'Preparation, Punctuality, Politeness, Persistence'], correctIndex: 0, topic: 'certification' },
  { prompt: 'Which statement about the credential is accurate?', choices: ['The 1P-CLC is a state-issued life coach license', 'The 1P-CLC is an accredited credential issued by an external coaching body', 'The 1P-CLC is a proprietary certification; the A.L.I.G.N. Practitioner License is the annually renewed right to deliver the framework commercially', 'The certification and the license are the same thing'], correctIndex: 2, topic: 'certification' },
  { prompt: 'A practice hour counts toward the 25-hour requirement when:', choices: ['You watched a coaching video', 'You logged a real coaching session and an admin approved the entry', 'You planned a session that did not happen', 'You attended the live weekly call'], correctIndex: 1, topic: 'certification' },
  { prompt: 'The written exam is:', choices: ['Timed, with a single attempt', 'Unlimited attempts at a 70 percent pass mark', '15 questions drawn at random, 80 percent to pass, up to three attempts, no timer', 'Graded by two members of your cohort'], correctIndex: 2, topic: 'certification' },
  { prompt: 'Annual renewal of the A.L.I.G.N. Practitioner License requires:', choices: ['Logged coaching hours plus continuing education credits', 'Retaking the written exam', 'Nothing, because the license does not expire', 'A newly recorded session each year'], correctIndex: 0, topic: 'certification' },
  { prompt: 'Your recorded session comes back for another take. The correct read is:', choices: ['Your certification has been denied', 'The rubric was applied to you unfairly', 'You must wait for the next cohort to resubmit', 'You have feedback, you practice, and you resubmit'], correctIndex: 3, topic: 'certification' }
];
