// 1P Certified Life Coach · written exam bank.
// Seeded to Firestore examBank/1p-clc/questions/q### by scripts/seed-clc.js.
// Each: { prompt, choices[4], correctIndex, topic }. startExam draws
// config/certification.examQuestionCount at random from active questions.

module.exports = [
  { prompt: 'A client asks, "What would you do in my situation?" The strongest coaching response is to:', choices: ['Share what worked for you, since they asked directly', 'Redirect with a question that returns ownership, such as "What options do you see?"', 'Decline to answer and change the subject', 'Give advice but label it clearly as advice'], correctIndex: 1 },
  { prompt: 'The five stages of A.L.I.G.N., in order, are:', choices: ['Awareness, Leadership, Identity, Growth, Navigation', 'Alignment, Learning, Intention, Goals, Navigation', 'Awareness, Listening, Identity, Growth, Negotiation', 'Action, Leadership, Insight, Growth, Navigation'], correctIndex: 0 },
  { prompt: 'A client repeatedly describes symptoms of clinical depression. The certified coach should:', choices: ['Design a habit plan to improve their mood', 'Coach harder on mindset', 'Refer them to a licensed mental health professional with care, and stay within coaching scope', 'End the engagement immediately without explanation'], correctIndex: 2 },
  { prompt: 'Level-three listening means hearing:', choices: ['The exact words the client says', 'The meaning behind the words', 'What is not being said: energy shifts, avoided subjects, repeated words', 'The advice the client is hoping for'], correctIndex: 2 },
  { prompt: 'Why does the 1P method work at the identity layer rather than the behavior layer alone?', choices: ['Identity work is faster', 'Behavior change that contradicts identity does not hold', 'Clients prefer talking about identity', 'Behavior change is impossible without a coach'], correctIndex: 1 },
  { prompt: 'The 1P session spine is:', choices: ['Small talk, problem, solution, homework', 'Intention, session goal, explore, insight, action, accountability', 'Review, advice, plan, close', 'Goal, obstacles, options, way forward, celebration, referral'], correctIndex: 1 },
  { prompt: 'A powerful coaching question is usually:', choices: ['Long and detailed so the client understands the context', 'Closed, so the client can answer quickly', 'Short, open, curious, and asked one at a time', 'Leading, so the client reaches the right conclusion'], correctIndex: 2 },
  { prompt: 'The 1P goal stack, in full, is:', choices: ['Outcome goals only', 'Outcome, identity, and process goals', 'Daily, weekly, and monthly goals', 'Stretch, realistic, and safety goals'], correctIndex: 1 },
  { prompt: 'Accountability in the 1P method is best described as:', choices: ['Applying pressure so the client performs', 'Honest measurement plus belief, never guilt', 'Checking in only when the client fails', 'Making the client report to you daily'], correctIndex: 1 },
  { prompt: 'A client agrees to every plan but completes none of them. The first coaching move is to:', choices: ['Assign smaller tasks', 'Explore ownership: whose goal is this, really?', 'Add more accountability check-ins', 'End the engagement'], correctIndex: 1 },
  { prompt: 'During a session the client falls silent after a strong question. You should:', choices: ['Rephrase the question immediately', 'Fill the silence with an example from your life', 'Hold the silence and let the client think', 'Move to the next agenda item'], correctIndex: 2 },
  { prompt: 'The discovery call exists primarily to:', choices: ['Close the sale as fast as possible', 'Serve the prospect with real clarity; the sale is a byproduct', 'Demonstrate how much you know', 'Qualify whether the client can afford you'], correctIndex: 1 },
  { prompt: 'Misalignment in a successful-on-paper client is most often rooted in:', choices: ['Laziness', 'A values conflict between what they say matters and how they operate', 'Lack of information', 'Too few goals'], correctIndex: 1 },
  { prompt: 'The four criteria of the certification rubric are:', choices: ['Presence and Listening, Question Quality, Session Structure, Non-Advising', 'Energy, Charisma, Knowledge, Closing', 'Empathy, Advice Quality, Speed, Results', 'Preparation, Punctuality, Politeness, Persistence'], correctIndex: 0 },
  { prompt: 'Which statement about the credential is accurate?', choices: ['The 1P-CLC is a state-issued life coach license', 'The 1P-CLC is an ICF-accredited credential', 'The 1P-CLC is a proprietary certification; the A.L.I.G.N. Practitioner License is the annually renewed right to deliver the framework commercially', 'The certification and the license are the same thing'], correctIndex: 2 },
  { prompt: 'A practice hour counts toward the 25-hour requirement when:', choices: ['You watched a coaching video', 'You logged a real coaching session and an admin approved the entry', 'You planned a session that did not happen', 'You attended the live weekly call'], correctIndex: 1 },
  { prompt: 'Confidentiality in a coaching engagement should be:', choices: ['Implied and never discussed', 'Stated in the agreement before coaching begins, with its limits named', 'Absolute with no exceptions of any kind', 'Optional for practice clients'], correctIndex: 1 },
  { prompt: 'The compounding logic at the heart of The One Percent is:', choices: ['Massive action in short bursts', 'Becoming one percent better every day through small, consistent, aligned progress', 'Working more hours than anyone else', 'Waiting for motivation before acting'], correctIndex: 1 }
];;
